### PR TITLE
Add an api option to toggle the debugger

### PR DESCRIPTION
**Pull request by SkySymbol**

### CODE REVIEW

**Comment by stevan** [comment]
Would you mind adding a simple unit test for this?

**Comment by stevan** [comment]
Looks good, thanks!

**Comment by SysPete** [comment]
This commit breaks `Plack::App::Debugger`:
```
Error:  Global symbol "$req" requires explicit package name at /home/apm/git/Plack-Debugger/lib/Plack/App/Debugger.pm line 130.
```
And the new test itself fails to compile after fixing up App::Debugger.

I've cooked up a quick branch https://github.com/SysPete/p5-plack-debugger/tree/fixup_pr_12 but since this PR doesn't appear to actually do anything apart from adding code (in the wrong place) I think a revert is a better option which is why I have not created a PR.

**Comment by stevan** [comment]
@SysPete actually your patch does fix it, please make it a proper pull request. 

It removes the `return $req`, which is wrong anyway, it should be `return ($req, undef)`, which is what happens anyway at the bottom of the subroutine if you remove those lines. Also, moving it down several lines means that `$req` is in scope and won't have that error you were seeing. 

Sorry, this was my fault, I didn't inspect the patch/pull-request well enough. Thankfully you caught this before it went out to CPAN.

**Pull request merged**
